development:
  adapter: mysql2
  encoding: utf8
  database: school_mgmt_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  database: school_mgmt_test
  pool: 5
  username: root